--TEST--
Bugfix #12: PDO::PARAM_BOOL should bind correctly as "1", "0", or NULL
--EXTENSIONS--
pdo
pdo_oci
--SKIPIF--
<?php
require(getenv('PDO_TEST_DIR').'/pdo_test.inc');
PDOTest::skip();
?>
--FILE--
<?php

require(getenv('PDO_TEST_DIR').'/pdo_test.inc');
$pdo = PDOTest::test_factory(getenv('PDO_OCI_TEST_DIR').'/common.phpt');

$pdo->exec("begin
    execute immediate 'drop table test_boolean_binding_12';
    exception when others then
    if sqlcode <> -942 then
        raise;
    end if;
end;");

$pdo->exec("CREATE TABLE test_boolean_binding_12 (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    flag NUMBER(1)
)");

// Insert true
$stmt = $pdo->prepare("INSERT INTO test_boolean_binding_12 (flag) VALUES (:flag)");
$stmt->bindValue(':flag', true, PDO::PARAM_BOOL);
$stmt->execute();

// Insert false
$stmt->bindValue(':flag', false, PDO::PARAM_BOOL);
$stmt->execute();

// Insert null
$stmt->bindValue(':flag', null, PDO::PARAM_NULL);
$stmt->execute();

// Integer 1 and 0 with BOOL param
$stmt->bindValue(':flag', 1, PDO::PARAM_BOOL);
$stmt->execute();
$stmt->bindValue(':flag', 0, PDO::PARAM_BOOL);
$stmt->execute();

// Binding by reference
$value = true;
$stmt->bindParam(':flag', $value, PDO::PARAM_BOOL);
$stmt->execute();

$value = false;
$stmt->execute();

$rows = $pdo->query("SELECT flag FROM test_boolean_binding_12 ORDER BY id")->fetchAll(PDO::FETCH_COLUMN);

foreach ($rows as $r) {
    var_export($r);
    echo "\n";
}
?>
--CLEAN--
<?php
require(getenv('PDO_TEST_DIR').'/pdo_test.inc');
$db = PDOTest::test_factory(getenv('PDO_OCI_TEST_DIR').'/common.phpt');
$db->exec("begin
             execute immediate 'drop table test_boolean_binding_12';
             exception when others then
               if sqlcode <> -942 then
                 raise;
               end if;
           end;");
?>
--EXPECT--
'1'
'0'
NULL
'1'
'0'
'1'
'0'
